name: Twitter App - Timeline Microservice Workflow

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ["self-hosted", "timeline"]
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: | 
        mvn -B package --file pom.xml
    - name: Run JAR File
      run: sudo kill -9 `sudo lsof -t -i:8085` & sudo nohup java -jar /home/ec2-user/twitter-app/timeline-microservice/actions-runner/_work/Twitter-App---Timeline-Microservice/Twitter-App---Timeline-Microservice/target/timelinemicroservice-jar-with-dependencies.jar &
